# Generated by Django 2.1 on 2021-01-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210101_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image',
            new_name='img',
        ),
    ]
